version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: stadiumpulse_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - stadiumpulse_net

  backend:
    build: ./backend
    container_name: stadiumpulse_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/stadiumpulse
      - JWT_SECRET=supersecretfifaworldcup2026stadiumpulsekey
      - GEMINI_API_KEY=
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - stadiumpulse_net

  frontend:
    build: ./frontend
    container_name: stadiumpulse_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - stadiumpulse_net

volumes:
  mongo_data:

networks:
  stadiumpulse_net:
    driver: bridge
